name: My Workflow
on: 
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "https://app.saul.angry.ventures/assets/images/uploads/qSj5CvdhJynjnK3.svg"
          replace: "img\\portrait_placeholder_2.3"
          regex: false
